# Generated by Django 3.1 on 2020-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='foo', max_length=64),
            preserve_default=False,
        ),
    ]
